In [4]:
import numpy as np

In [5]:
one_dimensional_array=np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [7]:
two_dimensional_array=np.array([[6,5],[11,7],[4,8],[2,5]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]
 [ 2  5]]


In [6]:
sequence_of_integers=np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [8]:
random_integers_between_50_and_100=np.random.randint(low=50,high=101,size=(6))
print(random_integers_between_50_and_100)

[81 74 96 84 97 87]


In [10]:
random_floats_between_0_and_1=np.random.random([6])
print(random_floats_between_0_and_1)

[0.83536975 0.30348471 0.84135256 0.08647017 0.7549674  0.55712673]


In [11]:
random_floats_between_2_and_3=random_floats_between_0_and_1+2
print(random_floats_between_2_and_3)

[2.83536975 2.30348471 2.84135256 2.08647017 2.7549674  2.55712673]


In [12]:
random_integers_between_150_and_300=random_integers_between_50_and_100*3
print(random_integers_between_150_and_300)

[243 222 288 252 291 261]


In [13]:
feature=np.random.randint(low=6,high=21,size=(15))
print(feature)

[10  6 15 18  8  6 12 20 11 13 16  7 18 20  6]


In [15]:
label=(3*feature)+4
print(label)

[34 22 49 58 28 22 40 64 37 43 52 25 58 64 22]


In [16]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [17]:
noise=(np.random.random([15])*4)-2
print(noise)
label=label+noise
print(label)

[-0.57489428 -1.44107067 -0.85886675  1.09434372 -0.04256864 -0.76709547
 -1.16511483 -0.14371074 -1.98326795  0.56636261  1.13939899 -1.80707315
 -1.21352609 -1.59513674  1.03719033]
[21.42510572 23.55892933 27.14113325 32.09434372 33.95743136 36.23290453
 38.83488517 42.85628926 44.01673205 49.56636261 53.13939899 53.19292685
 56.78647391 59.40486326 65.03719033]
